"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  ArrowLeft,
  CheckCircle,
  FileDown,
  Loader2,
  AlertTriangle,
  AlertCircle,
  Info,
  Copy,
  Check,
} from "lucide-react";
import { Protected } from "@/components/layout/protected";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { apiFetch } from "@/lib/api";
import { BillDetail, Finding, StandardResponse } from "@/lib/types";
import { formatCurrency, formatDate } from "@/lib/utils";
import { toast } from "sonner";

function severityBadge(severity: string) {
  switch (severity) {
    case "CRITICAL":
    case "HIGH":
      return (
        <span className="rounded-full bg-destructive/10 px-2.5 py-0.5 text-[11px] font-semibold text-destructive">
          High
        </span>
      );
    case "MEDIUM":
      return (
        <span className="rounded-full bg-warning/10 px-2.5 py-0.5 text-[11px] font-semibold text-warning">
          Medium
        </span>
      );
    default:
      return (
        <span className="rounded-full bg-success/10 px-2.5 py-0.5 text-[11px] font-semibold text-success">
          Low
        </span>
      );
  }
}

function severityIcon(severity: string) {
  switch (severity) {
    case "CRITICAL":
    case "HIGH":
      return <AlertTriangle size={16} className="text-destructive" />;
    case "MEDIUM":
      return <AlertCircle size={16} className="text-warning" />;
    default:
      return <Info size={16} className="text-success" />;
  }
}

/** Build a plain-text report from bill data */
function buildReport(bill: BillDetail): string {
  const findings = bill.findings ?? [];
  const lineItems = bill.line_items ?? [];
  const totalSavings = findings.reduce(
    (s, f) => s + (f.estimated_savings ?? 0),
    0
  );

  let text = `ACUVERA BILL ANALYSIS REPORT\n`;
  text += `${"=".repeat(40)}\n\n`;
  text += `File: ${bill.file_name}\n`;
  text += `Status: ${bill.status}\n`;
  if (bill.uploaded_at) text += `Uploaded: ${formatDate(bill.uploaded_at)}\n`;
  if (bill.total_amount)
    text += `Total Amount: ${formatCurrency(bill.total_amount)}\n`;
  text += `Issues Found: ${findings.length}\n`;
  text += `Potential Savings: ${formatCurrency(totalSavings)}\n`;
  text += `\n`;

  if (lineItems.length > 0) {
    text += `LINE ITEMS\n${"-".repeat(40)}\n`;
    lineItems.forEach((item, i) => {
      text += `${i + 1}. ${item.description}`;
      if (item.code) text += ` (${item.code})`;
      text += ` - ${formatCurrency(item.total_price)}\n`;
    });
    text += `\n`;
  }

  if (findings.length > 0) {
    text += `AI FINDINGS\n${"-".repeat(40)}\n`;
    findings.forEach((f, i) => {
      const label = f.type
        .replace(/_/g, " ")
        .replace(/\b\w/g, (l) => l.toUpperCase());
      text += `\n${i + 1}. ${label} [${f.severity}]\n`;
      text += `   ${f.explanation}\n`;
      if (f.recommended_action) text += `   Action: ${f.recommended_action}\n`;
      if (f.estimated_savings)
        text += `   Est. Savings: ${formatCurrency(f.estimated_savings)}\n`;
    });
    text += `\n`;
  }

  text += `${"=".repeat(40)}\n`;
  text += `Generated by Acuvera | ${new Date().toLocaleDateString()}\n`;
  return text;
}

export default function ClaimDetailPage() {
  const params = useParams();
  const id = params.id as string;
  const [bill, setBill] = useState<BillDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [polling, setPolling] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    async function loadBill() {
      try {
        const res = await apiFetch<StandardResponse<BillDetail>>(
          `/bills/${id}`
        );
        setBill(res.data);
        setLoading(false);
        if (
          res.data.status === "PROCESSING" ||
          res.data.status === "PENDING"
        ) {
          setPolling(true);
        } else {
          setPolling(false);
        }
      } catch {
        setBill(null);
        setLoading(false);
      }
    }
    loadBill();
  }, [id]);

  // Poll for completion (fallback for any bills still using background threads)
  useEffect(() => {
    if (!polling) return;
    const interval = setInterval(async () => {
      try {
        const res = await apiFetch<StandardResponse<BillDetail>>(
          `/bills/${id}`
        );
        setBill(res.data);
        if (
          res.data.status !== "PROCESSING" &&
          res.data.status !== "PENDING"
        ) {
          setPolling(false);
        }
      } catch {
        setPolling(false);
      }
    }, 5000);
    return () => clearInterval(interval);
  }, [polling, id]);

  const handleExport = useCallback(() => {
    if (!bill) return;
    const report = buildReport(bill);
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `acuvera-report-${bill.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Report downloaded.");
  }, [bill]);

  const handleCopyReport = useCallback(() => {
    if (!bill) return;
    const report = buildReport(bill);
    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      toast.success("Report copied to clipboard.");
      setTimeout(() => setCopied(false), 2000);
    });
  }, [bill]);

  const findings = bill?.findings ?? [];
  const totalSavings = findings.reduce(
    (s, f) => s + (f.estimated_savings ?? 0),
    0
  );

  return (
    <Protected>
      <DashboardLayout
        title={bill?.file_name ?? "Bill Details"}
        subtitle={
          bill?.uploaded_at
            ? `Uploaded ${formatDate(bill.uploaded_at)}`
            : "Loading..."
        }
        actions={
          <div className="flex items-center gap-2">
            <Button variant="ghost" asChild>
              <Link href="/claims">
                <ArrowLeft size={15} /> Back
              </Link>
            </Button>
            {bill?.status === "COMPLETED" && (
              <>
                <Button
                  variant="outline"
                  className="gap-1.5"
                  onClick={handleCopyReport}
                >
                  {copied ? (
                    <Check size={14} />
                  ) : (
                    <Copy size={14} />
                  )}
                  {copied ? "Copied" : "Copy Report"}
                </Button>
                <Button
                  variant="outline"
                  className="gap-1.5"
                  onClick={handleExport}
                >
                  <FileDown size={14} /> Download Report
                </Button>
              </>
            )}
          </div>
        }
      >
        {loading ? (
          <div className="space-y-4">
            {[...Array(3)].map((_, i) => (
              <div
                key={i}
                className="h-32 animate-pulse rounded-xl border border-border bg-card"
              />
            ))}
          </div>
        ) : polling ? (
          <Card className="flex flex-col items-center py-20 text-center">
            <Loader2
              size={40}
              className="mb-4 animate-spin text-primary"
            />
            <h3 className="text-base font-semibold text-foreground">
              AI Analysis in Progress
            </h3>
            <p className="mt-2 max-w-sm text-[13px] text-muted-foreground">
              Our AI is analyzing your medical bill for errors and savings.
              This usually takes 10-30 seconds. The page will update
              automatically.
            </p>
          </Card>
        ) : !bill ? (
          <Card className="flex flex-col items-center py-16 text-center">
            <p className="text-muted-foreground">Bill not found.</p>
            <Link
              href="/claims"
              className="mt-4 text-[13px] text-primary hover:underline"
            >
              Back to Claims Review
            </Link>
          </Card>
        ) : (
          <div className="space-y-6">
            {/* Summary Card */}
            <Card className="space-y-5">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-[12px] font-medium uppercase tracking-wider text-muted-foreground">
                    Bill #{bill.id}
                  </p>
                  <p className="mt-1 text-lg font-semibold text-foreground">
                    {bill.file_name}
                  </p>
                </div>
                <Badge
                  variant={
                    bill.status === "COMPLETED"
                      ? "success"
                      : bill.status === "FAILED"
                        ? "destructive"
                        : "neutral"
                  }
                >
                  {bill.status === "COMPLETED"
                    ? "Analysis Complete"
                    : bill.status === "FAILED"
                      ? "Analysis Failed"
                      : bill.status}
                </Badge>
              </div>

              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-lg bg-muted/50 p-4">
                  <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
                    Total Amount
                  </p>
                  <p className="mt-1 text-xl font-bold text-foreground">
                    {bill.total_amount
                      ? formatCurrency(bill.total_amount)
                      : "—"}
                  </p>
                </div>
                <div className="rounded-lg bg-muted/50 p-4">
                  <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
                    Issues Found
                  </p>
                  <p className="mt-1 text-xl font-bold text-foreground">
                    {findings.length}
                  </p>
                </div>
                <div className="rounded-lg bg-success/5 p-4">
                  <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
                    Potential Savings
                  </p>
                  <p className="mt-1 text-xl font-bold text-success">
                    {formatCurrency(totalSavings)}
                  </p>
                </div>
              </div>
            </Card>

            {/* Line Items */}
            {bill.line_items && bill.line_items.length > 0 && (
              <Card className="overflow-hidden p-0">
                <div className="border-b border-border px-6 py-4">
                  <h3 className="text-sm font-semibold text-foreground">
                    Line Items
                  </h3>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-[13px]">
                    <thead>
                      <tr className="border-b border-border bg-muted/40 text-left text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                        <th className="px-4 py-2.5">Description</th>
                        <th className="px-4 py-2.5">Code</th>
                        <th className="px-4 py-2.5 text-right">Qty</th>
                        <th className="px-4 py-2.5 text-right">
                          Unit Price
                        </th>
                        <th className="px-4 py-2.5 text-right">Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {bill.line_items.map((item) => (
                        <tr key={item.id}>
                          <td className="px-4 py-3 text-foreground">
                            {item.description}
                          </td>
                          <td className="px-4 py-3 text-muted-foreground">
                            {item.code ?? "—"}
                          </td>
                          <td className="px-4 py-3 text-right text-muted-foreground">
                            {item.quantity}
                          </td>
                          <td className="px-4 py-3 text-right text-muted-foreground">
                            {formatCurrency(item.unit_price)}
                          </td>
                          <td className="px-4 py-3 text-right font-medium text-foreground">
                            {formatCurrency(item.total_price)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </Card>
            )}

            {/* Findings */}
            <div>
              <h3 className="mb-3 text-sm font-semibold text-foreground">
                AI Findings
                {findings.length > 0 && (
                  <span className="ml-2 text-muted-foreground">
                    ({findings.length})
                  </span>
                )}
              </h3>
              {bill.status === "FAILED" ? (
                <Card className="flex flex-col items-center py-10 text-center">
                  <AlertTriangle
                    size={32}
                    className="mb-3 text-destructive"
                  />
                  <p className="text-[13px] font-medium text-foreground">
                    Analysis failed
                  </p>
                  <p className="mt-1 text-[12px] text-muted-foreground">
                    There was an error analyzing this bill. Please try uploading
                    again.
                  </p>
                </Card>
              ) : findings.length === 0 ? (
                <Card className="flex flex-col items-center py-10 text-center">
                  <CheckCircle
                    size={32}
                    className="mb-3 text-success"
                  />
                  <p className="text-[13px] font-medium text-foreground">
                    No issues detected
                  </p>
                  <p className="mt-1 text-[12px] text-muted-foreground">
                    This bill appears to be clean.
                  </p>
                </Card>
              ) : (
                <div className="space-y-3">
                  {findings.map((finding) => (
                    <FindingCard key={finding.id} finding={finding} />
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </DashboardLayout>
    </Protected>
  );
}

/** Map finding type to a human-readable category label */
function categoryLabel(type: string): { label: string; color: string } {
  switch (type) {
    case "OVERCHARGE":
      return { label: "Financial", color: "text-destructive" };
    case "DUPLICATE_CHARGE":
      return { label: "Financial", color: "text-destructive" };
    case "MISSING_DISCOUNT":
      return { label: "Financial", color: "text-warning" };
    case "INCORRECT_CODING":
      return { label: "Coding", color: "text-primary" };
    case "DENIAL_RISK":
      return { label: "Insurance", color: "text-warning" };
    default:
      return { label: "Review", color: "text-muted-foreground" };
  }
}

function FindingCard({ finding }: { finding: Finding }) {
  const typeLabel = finding.type
    .replace(/_/g, " ")
    .replace(/\b\w/g, (l) => l.toUpperCase());
  const cat = categoryLabel(finding.type);

  return (
    <Card className="space-y-3">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          {severityIcon(finding.severity)}
          <div>
            <h4 className="text-[13px] font-semibold text-foreground">
              {typeLabel}
            </h4>
            <div className="mt-1 flex flex-wrap items-center gap-2">
              {severityBadge(finding.severity)}
              <span className={`text-[11px] font-medium ${cat.color}`}>
                {cat.label}
              </span>
              <span className="text-[10px] text-muted-foreground">
                {(finding.confidence * 100).toFixed(0)}% confidence
              </span>
            </div>
          </div>
        </div>
        {finding.estimated_savings > 0 && (
          <div className="text-right">
            <p className="text-[11px] text-muted-foreground">Savings</p>
            <p className="text-sm font-semibold text-success">
              {formatCurrency(finding.estimated_savings)}
            </p>
          </div>
        )}
      </div>
      <p className="text-[13px] leading-relaxed text-muted-foreground">
        {finding.explanation}
      </p>
      {finding.recommended_action && (
        <div className="rounded-lg bg-muted/50 p-3">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
            Recommended Action
          </p>
          <p className="mt-1 text-[13px] text-foreground">
            {finding.recommended_action}
          </p>
        </div>
      )}
    </Card>
  );
}
